### ISSUE TITLE
Suboptimal lighting augmentation for ImageNet

### ISSUE THREAD

**Issue by DreamChaserMXF** [tensorpack/tensorpack#1085]
It seems to be suboptimal in the lighting augmentation for ImageNet in [imagenet_utils.py](https://github.com/tensorpack/tensorpack/blob/78595e71f4e770c62c630c52922fc8405e3ae509/examples/ImageNetModels/imagenet_utils.py#L205). 

>     def lighting(image, std, eigval, eigvec):
>        v = tf.random_uniform(shape=[3]) * std * eigval
>        inc = tf.matmul(eigvec, tf.reshape(v, [3, 1]))
>        image = tf.cast(tf.cast(image, tf.float32) + tf.reshape(inc, [3]), image.dtype)
>        return image

Since tf.random_uniform() produces uniformly sampled float values from [0, 1) as default and eigen vectors are valid in both directions, the random lighting vector added to the image pixels will be consistently inside a subspace of the 3D space spanned by the 3 eigen vectors from PCA.

Should it be `v=tf.random_uniform(shape=[3], minval=-1, maxval=1)` ?

**Comment by ppwwyyxx** [comment]
Thanks! The preprocessing should follow `fb.resnet.torch` (which is also used by many papers). The correct version is to use `random_normal`. Now it's fixed.

This does not affect any models because I only used dataflow-based preprocessing and these TF-based pre-processing are only there for benchmark.
