### ISSUE TITLE
Support FasterRCNN training/testing with batch>1 per GPU?

### ISSUE THREAD

**Issue by Remember2018** [tensorpack/tensorpack#1089]
Hi, in https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/NOTES.md, you noted that there maybe some possible enhancement for FasterRCNN in Tensorpack.
If convenient, could you please give some advice on how to support training/testing in FasterRCNN in Tensorpack with batch>1 per GPU? 

But I'm not sure how much GPU memory it takes for large batch training. In my experiment, for a GTX 1080 Ti, if we use ResNet50 backbone in FasterRCNN, training with short edge size of 800 and max size of 1333 will cost about 10Gb GPU memory. So if we use large batch, the GPU will out of memory. I don't know how the engineers in big company achieve the large batch training in FasterRCNN. Could you please give some advice? Thanks.

**Comment by ppwwyyxx** [comment]
> If convenient, could you please give some advice on how to support training/testing in FasterRCNN in Tensorpack with batch>1 per GPU?

It's much more complicated to implement than single-batch in tensorflow and that's why it is not supported. And I have no recent plans adding it, for reasons below.

> I don't know how the engineers in big company achieve the large batch training in FasterRCNN.

You're correct that it takes a lot of memory. Even with batch>1 support, standard models typically can run at most 3 images per batch, which is not very interesting or super useful.
Sure you can also run smaller models / smaller images, but those are not very interesting to me, either.

And of course, if you count the batch size over all GPUs you can get much larger batch size.

**Comment by Remember2018** [comment]
Yeah, understood. Thanks a lot! @ppwwyyxx .
