### ISSUE TITLE
Can we decouple some of the parameters in imgaug.geometry.Rotation._get_augment_params() ?

### ISSUE THREAD

**Issue by elmirador** [tensorpack/tensorpack#1096]
Related code:
https://github.com/tensorpack/tensorpack/blob/master/tensorpack/dataflow/imgaug/geometry.py#L84-L86

One can see that it actually returns a `WarpAffineTransform` class that keeps some of the *determined* parameters like `borderMode` and `borderValue`.

This can be inconvenient. Say, I want to rotate an RGB image with `borderValue=127.5` and naturally, want to rotate the pairing segmentation groundtruth label map with the same center and degree using `borderValue=255`:
```
rgb, _prms = imgaug.Rotation(15.0, (0.4, 0.6), border=cv2.BORDER_CONSTANT, border_value=127.5).augment_return_params(rgb)`
gt = imgaug.Rotation(15.0, (0.4, 0.6), border=cv2.BORDER_CONSTANT, border_value=255).augment_with_params(gt, _prms)
```

The rotation center and degree are preserved, but also the `borderValue`, renders the `border_value=255` useless.

Right now a hacky way to achieve the goal is changing the `WarpAffineTransform` class attribute manually.
One cleaner solution is return `(mat, img.shape[1::-1])` in `_get_augment_params()`, then construct the `WarpAffineTransform` class inside `_augment`. Determined parameters shouldn't be keeped here.

**Comment by ppwwyyxx** [comment]
My view of this is that you actually want to use two __different__ transformations on two different data (although they share some parameters), so it gets out of the abstraction of our "imgaug" module, so you need to do it manually in your dataflow.

Making the `Rotation` augmentor return less information in `get_augment_params` does not solve the problem of the imgaug abstraction. In your solution above you still need to construct two different transformations separately. The only difference after the change you proposed, is that you can then achieve what you want by writing less code, because the function would behave in a way that happen to be reusable by you. 

But I don't think this is a generic solution. It only makes the function more reusable if used it in a __non-standard__ way. Calling `augment_with_params` with `params` produced by a different augmentor instance is not the "official" usage and is also hacky: if you use different angles in the two `Rotation` instances, the same issue still arises. Because what you need is just fundamentally not supported by Augmentor.

**Comment by elmirador** [comment]
I get where you come from. You're considering all parameters inside the `cv2.warpAffine` function as the transformation. I only consider the `mat` parameter as the transformation since it's the core of the rotation.

> Calling augment_with_params with params produced by a different augmentor instance is not the "official" usage and is also hacky
Seems like my goal is just not achievable by using `imgaug` normally lol. I'll close this issue.
