### ISSUE TITLE
running multi-pod with multi-gpu,each pod contains four or more gpu cards,but according to your guideline,all pods can running,but happen a probelem,so list version of each component version

### ISSUE THREAD

**Issue by perrynzhou** [tensorpack/tensorpack#1150]
### 1. Running Multi-Pod With Multi-GPUS:

(1) **Multi-Pods Running Four Or More GPUS,Each Pod Contains Four GPUS**

(2) **Running Script For Python(imagenet-xxx.py) From Your Project**

(3) **Parameter Is The Same To Your Example**

### 2. I observed:

(1) **communication between gpu can't work**

(2) **gradient not be update between gpus**

### 3. What you expected, if not obvious.

(1)**description for your guiedeline too sample?**
(2)**can you give me details document about your case with multi-machine with multi-gpus?**

### 4. Your environment:
  + Python version: python3
  + Hhorovod version:0.16.0
  + Tensorpack version: 0.9.4

### 5. My Script
- each pod contains four gpus
```
mpirun --allow-run-as-root -np 4 -mca plm_rsh_args '-p 22' --oversubscribe   -mca plm_rsh_args '-p 22' --bind-to none -map-by slot -mca pml ob1 -x NCCL_IB_CUDA_SUPPORT=1 -x NCCL_IB_DISABLE=0 -x NCCL_DEBUG=INFO \
                      --mca btl_tcp_if_include 10.211.0.0/16   python3 imagenet-resnet-horovod.py  -d 50 --data /data/  --load ${LOG_DIR}/model-134060 --eval --no-zmq-ops
```

**Comment by ppwwyyxx** [comment]
Please include these information as requested in the issue template:


(1) **If you're using examples, what's the command you run:**

(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**

(3) **If not using examples, tell us what you did:**

  It's always better to copy-paste what you did than to describe them.

  Please try to provide enough information to let other __reproduce__ your issues. 
  Without reproducing the issue, we may not be able to investigate it.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**

It's always better to copy-paste what you observed instead of describing them.

**Comment by ppwwyyxx** [comment]
Closing since there is no response after a week.
