### ISSUE TITLE
How to use Callback only if train_op is being executed?

### ISSUE THREAD

**Issue by rahul003** [tensorpack/tensorpack#1160]
I want to use a callback only if training is going on because during other sess.run (such as initialization) it causes a crash because certain placeholders are empty.

How do I set the predicate in CallbackOnlyIf to only activate when training.

**Comment by ppwwyyxx** [comment]
If you want to know whether `train_op` is depended on by some given ops, use [dependency_of_fetches](https://tensorpack.readthedocs.io/modules/tfutils.html#tensorpack.tfutils.dependency.dependency_of_fetches)

For semantics of callback methods see https://tensorpack.readthedocs.io/tutorial/extend/callback.html

I'm not sure what it is you're asking. If the above does not help you, please clarify how do you define "when training"  or "training is going on". Technically, you cannot do anything when `train_op` is being executed because Python needs to wait for it to finish.

**Comment by rahul003** [comment]
That helped, thanks!
