### ISSUE TITLE
MultiProcessPrefetchData problem

### ISSUE THREAD

**Issue by Seraphli** [tensorpack/tensorpack#1231]
### 1. What you did:

Tensorpack 0.9.5
Test dataflow API. I ran this following code.

```
from tensorpack.dataflow import DataFlow, BatchData, MultiThreadPrefetchData, \
    TestDataSpeed, MultiProcessPrefetchData
import numpy as np


class MyDataFlow(DataFlow):
    def __init__(self):
        self.n_observations = int(1e5)
        self.feature = np.random.randint(0, 5, self.n_observations)
        self.i = 0

    def __len__(self):
        return self.n_observations

    def reset_state(self):
        self.i = 0

    def __iter__(self):
        for i in range(self.n_observations - 1):
            for m in range(100):
                for n in range(100):
                    pass
            yield self.feature[i], self.feature[i + 1]
            self.i += 1


df = MyDataFlow()
ds = BatchData(df, 32)
# df = MultiThreadPrefetchData(lambda: ds, 5000, 2)
df = MultiProcessPrefetchData(ds, 500, 2)
TestDataSpeed(df, size=10000).start()
```

### 2. What you observed:

When using multi-thread method, the progressbar finished with 100%.
```
100%|###################################################################################################################################|10000/10000[01:03<00:00,157.07it/s]
```

When using multi-process method, the progressbar will stop after iterate 3125 items.
```
[0612 16:25:40 @parallel.py:194] [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0612 16:25:40 @argtools.py:146] WRN Starting a process with 'fork' method is not safe and may consume unnecessary extra memory. Use 'forkserver' method (available after Py3.4) instead if you run into any issues. See https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
 31%|#########################################2                                                                                          |3125/10000[00:09<00:20,339.07it/s]
```
I tested several times and this issue happened every time. So I assume there are some errors.

PS:
Add `file=sys.stdout` option to tqdm will fix the pbar color issue on Pycharm.

**Comment by ppwwyyxx** [comment]
It stops at 3125 because it is the size of your dataflow (1e5 // 32).

It does not stop at 3125 for the multi-threaded one because the multi-threaded one does not properly handle the size for now.

Note that as mentioned in https://tensorpack.readthedocs.io/modules/dataflow.html#tensorpack.dataflow.DataFlow.__len__, the size is only a rough guidance and is not always well-defined or correct. 
Although in this particular case it would be better to make the multi-thread and multi-process dataflow consistent with each other. Therefore marked as a feature request.

**Comment by Seraphli** [comment]
@ppwwyyxx It seems the document is still using MultiProcessRunner, but the API in the pip package has been updated to MultiProcessPrefetchData. So do you plan to update the document recently?

**Comment by ppwwyyxx** [comment]
The document is correct (since it is built from master), and the pip package is lagging behind (it is built from last release tag).

**Comment by Seraphli** [comment]
Okay

**Comment by Gouiaa** [comment]
@Seraphli   I got this warning alos when I use `prefetchdatazmq`

**WRN Starting a process with 'fork' method is not safe and may consume unnecessary extra memory. Use 'forkserver' method (available after Py3.4) instead if you run into any issues.** 
I think it causes really a problem of memory because on GTX 1080, I could not use more than batch_size=2 (image_size 512*512*3). How to remove this warning?

**Comment by ppwwyyxx** [comment]
1. The warning itself already has information on using a different method (see python documentation): https://github.com/tensorpack/tensorpack/blob/c9fde6302a11a06acf53a378adf18a2a579276fe/tensorpack/utils/concurrency.py#L240-L242

2. This warning affects CPU memory. It does not affect GPU memory and unrelated to your GPU model.

Your problem is unrelated to this issue. If you still have unexpected issues, please open a new issue following the issue template.

**Comment by lhoangan** [comment]
@Seraphli @DeeperDeeper I'm running into the similar problem with the Warning and training is stopped midway. Upon inspecting, it was because of the dataloader memory consumption (100% of 120G) and thus got killed by slurm. Any idea how it was solved?
