### ISSUE TITLE
Quantization-aware model training and inference

### ISSUE THREAD

**Issue by Fzark100** [tensorpack/tensorpack#1232]
Hello!
I am attempting to using tensorpack, quantization-aware training, and toco to generate 8-bit tflite model file.
I used **"create_training_graph()"** in the training code, which  add fake quantization operations to the graph, and trained a model with 4 GPUs. 
Then I want to use **"create_eval_graph()"** to rewrite the graph and load the params from the ckpt. The problem is the valueables in ckpt have **"tower0/"**, **"tower1/"** in their name, but in the rewritten graph, they do not. I wonder how to solve such mismatch problem.

I follow the course in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/quantize

Here is the the log of the export.

[1.log](https://github.com/tensorpack/tensorpack/files/3280665/1.log)

**Comment by ppwwyyxx** [comment]
I don't think I understand your question, since a large part of it seems to be related to your own code.
But in general, there is no reason for a training graph to have the same node/tensor names as the evaluation graph. A model may very often perform different operations in training vs evaluation. 
The only things from training that need to be used in evaluation are the variables and they are saved in the checkpoint without any prefix.

**Comment by Fzark100** [comment]
The only difference is I added **tf.contrib.quantize.create_training_graph** and **tf.contrib.quantize.create_eval_graph** in the tensorpack's code. It seems I used them in wrong way. Do you have any idea about these two functions?

**Comment by ppwwyyxx** [comment]
I have no knowledge about these functions and in general don't trust functions I don't understand.
