### ISSUE TITLE
How to show all tf.summary.image from all towers?

### ISSUE THREAD

**Issue by Remember2018** [tensorpack/tensorpack#1234]
I'm using the FasterRCNN module in Tensorpack. In the `build_graph` function of the model definition, I added some `tf.summary.image` to show the images during training. And I use 4 GPUs to train and each GPU card have two images. To my understanding, there should be 4 `tower` in the summaries. But there is just one `tower0` in the tensorboard. Is there any related configuration on this? Thanks!

**Comment by ppwwyyxx** [comment]
Tensorpack removes summaries not from the first tower since this is the expected behavior most of the time.
To add custom summaries, use a different collection by `tf.summary.image(collections=["test"])`.
And summarize this collection by the callback `MergeAllSummaries(key="test")`.
See https://tensorpack.readthedocs.io/tutorial/summary.html

**Comment by Remember2018** [comment]
Hi Yuxin, @ppwwyyxx Thank you very much for your kind comment!
