### ISSUE TITLE
tensorpack.utils.loadcaffe Converting a Caffe model to tensorpack failed！！！

### ISSUE THREAD

**Issue by chuangchuangtan** [tensorpack/tensorpack#1292]
Unexpected Problems ：hi.I got SE-ResNet-50.prototxt and SE-ResNet-50.caffemodel from https://github.com/hujie-frank/SENet ,
and then convert caffe model to npz format by 'python -m tensorpack.utils.loadcaffe PATH/TO/{SE-ResNet-50.prototxt,SE-ResNet-50.caffemodel} SE-ResNet-50.npz '
so I got SE-ResNet-50.npz and no error.but it's different from tensorpack official model --‘http://models.tensorpack.com/ResNet/ImageNet-ResNet50-SE.npz’ ，by the way，I have renameed model，and the maximum and minimum of same matix is different，for example ‘ResNet50-SE/linear/W_0.npy’.
thank you,good luck

**Comment by ppwwyyxx** [comment]
>  it's different from tensorpack official model --‘http://models.tensorpack.com/ResNet/ImageNet-ResNet50-SE.npz’

I don't know what do you mean by "different". It would be more clear if you could post follow the issue template.

If you mean the values are different: this is expected because the models in tensorpack is not converted from caffe. It is a model trained in tensorpack.

Also, there is no guarantee that the model architecture is identical between the caffe model and the SE implementation in tensorpack. Different framework has small implementation differences which one needs to manually verify.

**Comment by chuangchuangtan** [comment]
Thanks and close issue.
