### ISSUE TITLE
How to stop training of example FasterRCNN

### ISSUE THREAD

**Issue by linzaihui** [tensorpack/tensorpack#1331]
Hello, I want to stop FasterRCNN training, but when I use `kill &lt;pid&gt;'，some processes are still alive.
```
 1405 pts/0    S      0:00 /usr/bin/python3 -c from multiprocessing.semaphore_tracker import main;main(3)
 1441 pts/0    Sl     0:46 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=4, pipe_handle=19) --multiprocessing-fork
 1442 pts/0    Sl     0:43 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=4, pipe_handle=20) --multiprocessing-fork
 1443 pts/0    Sl     0:51 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=4, pipe_handle=21) --multiprocessing-fork
 1444 pts/0    Sl     0:40 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=4, pipe_handle=22) --multiprocessing-fork
 1445 pts/0    Sl     0:45 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=4, pipe_handle=23) --multiprocessing-fork
 1597 pts/0    Sl     0:05 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=4, pipe_handle=31) --multiprocessing-fork
```
Is there any better way to stop training?

**Comment by ppwwyyxx** [comment]
Could you include your environment information following the [issue template](https://github.com/tensorpack/tensorpack/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems---bugs.md)?

4. Your environment:
Paste the output of this command: python -c 'import tensorpack.tfutils as u; print(u.collect_env_info())' If this command failed, tell us your version of Python/TF/tensorpack.

Note that:

You can install Tensorpack master by pip install -U git+https://github.com/ppwwyyxx/tensorpack.git and see if your issue is already solved.
If you're not using tensorpack under a normal command line shell (e.g., using an IDE or jupyter notebook), please retry under a normal command line shell.
You may often want to provide extra information related to your issue, but at the minimum please try to provide the above information accurately to save effort in the investigation.

**Comment by linzaihui** [comment]
thx for your reply. 
```
sys.platform          linux
Python                3.6.0 (default, Dec 24 2018, 17:02:27) [GCC 5.4.0 20160609]
Tensorpack            v0.9.8-0-gb6318616
Numpy                 1.15.4
TensorFlow            1.12.0/v1.12.0-0-ga6d8ffae09
TF Compiler Version   4.8.5
TF CUDA support       True
TF MKL support        False
Nvidia Driver         /usr/lib/nvidia-384/libnvidia-ml.so.384.130
CUDA                  /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart.so.9.0.176
CUDNN                 /usr/lib/libcudnn.so.7.1.4
NCCL                  /usr/lib/x86_64-linux-gnu/libnccl.so.2.4.8
CUDA_VISIBLE_DEVICES  None
GPU 0,1,2             GeForce GTX 1080 Ti
Free RAM              61.99/62.83 GB
CPU Count             12
cv2                   4.1.0
msgpack               0.6.1
python-prctl          False
```

**Comment by ppwwyyxx** [comment]
Could you install `python-prctl` and retry? https://pythonhosted.org/python-prctl/

Tensorpack logs probably have told you that some processes will be left if it is not installed.

**Comment by linzaihui** [comment]
Thank you, solved.
