### ISSUE TITLE
How to let the dataflow know the current epoch number?

### ISSUE THREAD

**Issue by JesseYang** [tensorpack/tensorpack#1360]
In some scenarios, it is better for the dataflow to feed different kinds of data as the training steps increases. For example, increasing the sequence length when training a speech recognition model. Is it possiple to let the dataflow (especially the get_data method) know the current training epoch number?

**Comment by ppwwyyxx** [comment]
Any iterable can be a dataflow so in the most general case you can always access `trainer.epoch_num` in your dataflow. However that means some of the builtin tools about multiprocessing will need more effort to work since the processes don't have access to the information available in trainer.


An alternative is just to pass some epoch length to your dataflow and let it do this independently.

**Comment by JesseYang** [comment]
@ppwwyyxx Thank you!
