### ISSUE TITLE
Training on custom dataset - only images and mask PNG files available

### ISSUE THREAD

**Issue by vijaygill** [tensorpack/tensorpack#1380]
Hi,

I tried searching using keywords like png / masks / custom dataset but could seem to find answer to my query.

I am trying to use tensorpack to train on a dataset which I am already using with MatterPort MaskRCNN. The dataset I have has images and mask files (png) which define masks for objects in those images(0 = BG, 1 = FG).

I do not have bounding polygons in COCO (or any textual) format. Bounding boxes can be calculated from masks, but polygons is what stops me from testing tensorpack.

Thanks.

**Comment by ppwwyyxx** [comment]
The polygons are converted to masks eventually (after augmentation) at https://github.com/tensorpack/tensorpack/blob/ffd9eaeb68fff978af23156236df661981017941/examples/FasterRCNN/data.py#L131-L141

so you can add code that handles masks directly.

You may not be able to easily use it for evaluation, because the COCO api may not support masks very well.

Nevertheless, you can convert masks to polygons using `cv2.findContours`.

**Comment by vijaygill** [comment]
> Nevertheless, you can convert masks to polygons using `cv2.findContours`.

Now why didn't I think of that! Thank you for a great tip! I will try it soon.

**Comment by vijaygill** [comment]
@ppwwyyxx Finally I got the chance to setup training today and within an hour I had training going. Thanks for your help!
