### ISSUE TITLE
[Usage Question] How to write a ModelDesc that is partially from a meta_graph file.

### ISSUE THREAD

**Issue by EchoWho** [tensorpack/tensorpack#790]
Suppose I have some meta graphs and associated checkpoints, and I want to initialize part of my model from them, how do I do this within tensorpack? E.g., I want to construct the first five layers from the meta_graph (from input to layer five), find the tensors of the layers using get_tensor_by_name, and add more functionality to the model using these layers. 

My specific question is on how to use InputDesc/ModelDesc in tensorpack for placeholders that are to be loaded from meta graphs, because constructing them using the standard ModelDesc::_get_inputs() would duplicate them. 

I noticed that there is a function called inputs() in ModelDesc, but it constructs the placeholders on a temporary graph. The meta graphs can be large, so initializing the meta graphs on the temporary graph just for the placeholders is undesirable

**Comment by ppwwyyxx** [comment]
In tensorflow, loading a metagraph and modifying it for training is NEVER a good idea. It almost always causes undesired trouble. In general you should write python code to recreate your model, and only load variables from a checkpoint.

**Comment by EchoWho** [comment]
Thanks for the prompt reply. Do you mind pointing me to references of why modifying metagraph for training is not a good idea?

**Comment by ppwwyyxx** [comment]
To load a model for training, conceptually what's needed to be loaded is some mathematical model plus the variables. MetaGraph (or graph) is not the right abstraction for it.

A metagraph contains the entire graph. For the one saved by tensorpack, it includes not only the mathematical model, but also the training settings: queues, data iterators, placeholders, evaluations, summaries, collections. Loading all of these settings from the last training means it will be very hard (if possible at all) to change them - essentially making the entire tensorpack not functional. In general as long as you want to make changes to the last training settings, it's going to be problematic to load a metagraph.

The tensorpack way to work around this problem is to encourage writing the mathematical model by python and load variables only.

Another way is the tensorflow-hub way: provide a "cleaner" version of metagraph (but not the actual graph used in training) that only contains the math, and use many hacks during `import_meta_graph` to avoid bad interaction between the imported graph and the existing graph.
