### ISSUE TITLE
Why is the entire dataset not cached by the end of first epoch?

### ISSUE THREAD

**Issue by trivikram29** [tensorpack/tensorpack#798]
Hi,
I ran the imagent-resent.py [https://github.com/tensorpack/tensorpack/blob/master/examples/ResNet/imagenet-resnet.py] from tensorpack examples using the below command.
"./imagenet-resnet.py --data /disk1/raw-data/ -d 50"

At the end of the first epoch, the cache size is around 85 GB (less than 145 GB imagenet data size)
Even after the second epoch has started, read ops are going to ssd.(at end of second epoch cache size is 130 GB).

I collected the above stats using cachestat command. I confirmed reads are going to ssd(in 2nd epoch) using iostat.
Moreover, the cache hit ratio keeps increasing slowly to 70%  by the end of first epoch and then close to 100% by the end of 2nd epoch.

I have sufficient dram to cache entire dataset (> 200 GB).
2 GPUs (v100)
Tensorpack version is 0.8.5
TensorFlow version is 1.6.0
Python Version 2.7.12

Why is the entire dataset not cached by the end of first epoch?

**Comment by ppwwyyxx** [comment]
Tensorpack simply reads them, and does nothing about caching. It's up to your operating system.

**Comment by ppwwyyxx** [comment]
After some investigation and communication on gitter, it turns out that it is an expected behavior that not all files are cached.
Since each worker created by `PrefetchDataZMQ` randomly produces images independently, when the number of workers is larger than one, there will be duplication and therefore not all files are read.
To ensure a whole dataset is used, use indices + `MultiProcessMapData` (https://github.com/tensorpack/tensorpack/pull/794#issuecomment-398429188)

Some more details:
Assuming there are K workers, each worker will create a local shuffle and produce roughly the first N/K images in the first epoch. The probability for a particular worker to produce a particular image is 1/K.
The probability an image will not appear in the first epoch will be `[(K-1)/K]^K`.
When K=40, this number is 0.36 so the cache will be 64% full. Considering the prefetching the cache should be a little bit more than 64% full.
