### ISSUE TITLE
could not convert BatchDescriptor

### ISSUE THREAD

**Issue by shineEtern** [tensorpack/tensorpack#828]
Hi, I run the FasterCNN example, and use COCO-R50C4-MaskRCNN-Standard.npz in model zoo to evaluate. The tensorflow version is 1.4. It is really hard for to update the tensorflow version because of the unmatched cuda and the old environment is still using. 
So How can I fix the problem as follows and run successfully on the version of 1.4? Thank you.
[0716 17:43:01 @sessinit.py:220] Restoring from dict ...
loading annotations into memory...
Done (t=0.82s)
creating index...
index created!
[0716 17:43:05 @coco.py:76] Instances loaded from ./coco/annotations/instances_minival2014.json.
100%|████████████████████████████████████| 5000/5000 [00:00<00:00, 98645.87it/s]
[0716 17:43:05 @timer.py:48] Load Groundtruth Boxes for minival2014 finished, time:0.0572sec.
  0%|                                                     |0/5000[00:00<?,?it/s][0716 17:43:05 @argtools.py:152] WRN Install python-prctl so that processes can be cleaned with guarantee.
 10%|####4                                      |516/5000[02:23<21:50, 3.42it/s]2018-07-16 17:45:29.054788: F tensorflow/stream_executor/cuda/cuda_dnn.cc:430] could not convert BatchDescriptor {count: 0 feature_map_count: 1024 spatial: 28 28  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX} to cudnn tensor descriptor: CUDNN_STATUS_BAD_PARAM
Aborted (core dumped)

**Comment by shineEtern** [comment]
I have added the tf.cond() in the ResNetFPNModel
function as follows, but  still  has this problem, how can I fix it? Thank you.
![_20180716211806](https://user-images.githubusercontent.com/37856730/42760746-fafa8ad8-893d-11e8-9aeb-5fdd8e6e36b1.png)

**Comment by ppwwyyxx** [comment]
You need to do similar things for `mask_rcnn_head_func` as well. I'm not sure if there are other places you need to also hack around.

Also, the `ff_false` part should return `[0, ncls, 4]` as the second element, although it was `ncls-1` in an earlier version.

I'm closing since the reason I drop TF 1.4 support is exactly because it's annoying and I don't want to deal with it more, especially for FPN. Hope you can solve it and get it running with my above comments. You can install a new version of TF with old cuda by compiling from source.

**Comment by shineEtern** [comment]
Thanks for your quick response!
