### ISSUE TITLE
How to make Conv2D ditributable outside tensorpack?

### ISSUE THREAD

**Issue by MrWanter** [tensorpack/tensorpack#846]
I'm using `Conv2D` outside tensorpack trainer, the network constructed can running correctly on one machine, however, when I distributed the training on multiple machines, the variables created by `Conv2D` seems belongs to some local variable, why `silim.con2d` can work as expected, I'm wondering if there are arguments like 
`Conv2D(global_variable=True)`

**Comment by ppwwyyxx** [comment]
Please post issues following the issue template.

1. Depend on what trainer you're using. Some trainer make variables local by design. Is there any reason you want them global?

2. You're recommended to use `HorovodTrainer` for distributed training. TensorFlow is not actively supporting its native distributed training features.
