### ISSUE TITLE
having official tensorflow model repository made available in tensorpack

### ISSUE THREAD

**Issue by Coderx7** [tensorpack/tensorpack#882]
Since `tensorpack` is nearly 2x - 5x times faster than other high-level wrappers such as `tf.slim` and `keras`, it would be very good to have the official model repository made available in `tensorpack` as well. 
Currently, the first place people such as me go to in order to obtain an efficient and correct implementation of major models is [Tensorflow official Model repository](https://github.com/tensorflow/models). 
The good thing about this repository is that everything is neatly organized and provided, so one can easily train a model and achieve the reported accuracy. it is also a breeze to initiate any training since everything is already there and explained very well from A to Z.
This simply makes porting new architectures a breeze since one can use the existing code and alter them to easily implement new models. especially newcomers to TF (and those that only want to make their work available in `Tensorflow` as well, myself included) 
However, the catch here is, the models are not efficiently implemented there. at least as efficient as `tensorpack` can be. It would be great to have those models reimplemented and ran using `tensorpack`. 
I believe since pretty much everything is already implemented (preprocessing routines, model definitions) in `Tensorflow`, there shouldn't be a major issue in doing this. I believe this effort will undoubtedly result in a further spread of this great addition to the TF community and hopefully make everything faster and better.

and thank you very much for your hard work and great achievement, it is indeed very plausible and wonderful work. 

Best Regards,
Hossein

**Comment by ppwwyyxx** [comment]
I think most code in [tensorflow/models/research](https://github.com/tensorflow/models/tree/master/research) are too specific (therefore only useful to a small group of people) or poorly maintained.

The imagenet models there https://github.com/tensorflow/models/tree/master/research/slim are worth porting. Some of the translation models also look good but I'm not very familiar with them.

**Comment by PatWie** [comment]
Porting these models is merely a copy paste / import action (tensorpack already supports TF.slim). I wonder if it is worth spending time in porting these imagenet-based models over.
Do you really want to compete with a repo which is apparently the first choice of people -- independent of the code-readability? You cannot convince people to make a wise choice (have a look at the keras fanbase).

The work would be redundant and is first and foremost time consuming work.
And I am not sure if one needs to retrain them anyway again and again.

The [CaffeModel Zoo](
https://github.com/BVLC/caffe/wiki/Model-Zoo) is IMHO much more interesting and diverse: DeepHand, VQA, some face-recognition stuff, semantic segmentation. 

There are bigger opportunities:
My concern is that there is currently a huge gap is the tensorpack documentation of how to convert a trained model in tensorpack to production (tensorflow-serving, tf-mobile, freeze graph stuff). Since tensorpack already uses ModelDescr and has a PredictConfig being able to build the inference only graph, it would be much more straightforward to export models from tensorpack than the way described in the official TF docs (including pruning the graph). The "apply" function in the examples is almost doing it.

I can check if the tfutils/export.py still works and phrase a first documentation draft. It would be huge plus if the entire pipeline is described and supported rather than adding more image classification models.

But in the end it is: Training takes time and a proper implementation as well. I do have a mobilenet implementation and I can contribute my cityscape data reader. However, we agree that it is most of the time tedious work to just get the model correct.

This is not a wishlist of new examples (time is limited). It is a slightly different (and more broad) view on the topic.

**Comment by ppwwyyxx** [comment]
I was thinking only one or two files, that construct the network by importing their code and do the inference. That provides an easy access to those pretrained models. 
I would not want to train them again or copy-paste their code.

**Comment by Coderx7** [comment]
You are correct that this is not a high priority subject or even one to consider at all. But what I'm trying to convey here is not copy-pasting the code from an old repository to a newer one, but rather providing a base with more efficient implementation matters.
To me it makes no sense I spend twice or 5x the time on training something while I can easily have a massive speedup using tensorpack! this is currently the issue. 
In order to address that, one way would be to port everything to tensorpack and training them to show that everything works as expected. Another way that's much suitable I guess would be to specify the bottlenecks and explain in the documentation that how one can overcome them. to be more exact, how to make an existing TF implementation run faster. (what would you do to make them run faster? what would you change and why?) 
I saw an example of this concerning datasets in the documentation. an explanation of how to go about such things would be enough and would have the same outcome of porting everything to tensorboard except that the contributors will be doing it.

**Comment by tingxingdong** [comment]
Why the pretrained model here is *npz format (http://models.tensorpack.com/)
While, TF hosted ones are *pb (https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md). 

Is there anyway convert from *npz to *pb format? Thankyou.

**Comment by tingxingdong** [comment]
We want to convert TF format to TF Lite format. According to TOCO, *npz is not supported yet, as I know.

**Comment by ppwwyyxx** [comment]
The [npz format](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.savez.html) contains key-value pairs that stores the trained parameters. With the example code that builds the graph, it is sufficient to restore and use the model, because now you have both the graph and its parameters.

However, if you want to use the model with a particular tool, you'll need to figure out what format it needs and how to construct a model which the tool can use. Maybe the `export_compact` function in `examples/basics/export-model.py` can help, but it all depends on what your tool needs. I'm not familiar with TOCO and inference tools are out of the scope of tensorpack.

**Comment by tingxingdong** [comment]
Thanks so much. I read the file: https://github.com/tensorpack/tensorpack/blob/master/examples/basics/export-model.py

But I do not quite get the comments

1. train the model by
    python export.py
2. export the model by
    python export.py --export serving --load train_log/export/checkpoint
    python export.py --export compact --load train_log/export/checkpoint

Which export.py it refers to (maybe export-model.py)?  
Suppose I have already download the "ShuffleNetV2-1x.npz" ( I think I can skip step 1 training, right? but I do not have dir train_log), what should I do next in order to obtain *.pb ?  Can you give more instructions. Thank you.

**Comment by ppwwyyxx** [comment]
> Which export.py it refers to (maybe export-model.py)?
Yes. `export-model.py`.

You can copy the `export_compact` function into your shufflenet code:
```python
    pred_config = PredictConfig(
        session_init=get_model_loader(model_path),
        model=MyShuffleNetModel(),
        input_names=['my input names'],
        output_names=['output names I need'])
    ModelExporter(pred_config).export_compact('/tmp/compact_graph.pb')
```
This gives you a serialized `tf.Graph` as a pb file but you need to figure out whether this pb file is in the same format that your tool needs. "pb file" is not a format.

**Comment by tingxingdong** [comment]
Thanks so much for quick reply and patience. I insert the following code after line 249 of 
https://github.com/tensorpack/tensorpack/blob/master/examples/ImageNetModels/shufflenet.py

    pred_config = PredictConfig(
        session_init=get_model_loader(args.load),
        model = Model()
        #, input_names=['input']
        #, output_names=['output']
        )
    ModelExporter(pred_config).export_compact('/tmp/compact_graph.pb')

I used command" python ./shufflenet.py --load ShuffleNetV2-1x.npz --v2 -r=1"

It gvies me AssertionError: <type 'NoneType'> which is model=Model() on line 252 , 
However, line 249 is exactly the model=Model() which passed before this block. 

Another question is what is the input_names & and output_names should I put? I can view the *npz file by 
```
x.np.load()
print name = x.files 
```
It gives me such names like "stage/4/block3/dconv_bn/variance/EMA:0", etc 
but I do not know who are input names and who are output names.

**Comment by ppwwyyxx** [comment]
Your question is unrelated to this issue. Please open a new one and follow the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md)).
`input_names` and `output_names` can be any tensor defined in the graph. If you want to input an image, the name of that tensor is "input".

**Comment by ppwwyyxx** [comment]
It seems that while TF is been moved to TF2, the official model repo will be unmaintained and rely on deprecated slim. Therefore closing this issue.
It's likely that TF will create a new set of pre-trained models/code for TF 2 and we can asses it then.
