### ISSUE TITLE
Add examples to tensorpack import

### ISSUE THREAD

**Issue by PatWie** [tensorpack/tensorpack#918]
I vote for adding the examples to the tensorpack (at least add a `__init__.py`). I end up with copying or symlinking these files. But something along

```python
from tensorpack.examples.GAN import GanTrainer
from tensorpack.examples.OpticalFlow.FlowNet import Model
```

would be super useful. I know, these examples might change. But the same is true for symlinks. And ending with several copies of the same file is neither a good solution.

**Comment by ppwwyyxx** [comment]
I would recommend you to copy them because those code can change in any incompatible ways. This is how I work now. I would not want to see a new user starting to import these.
What about a huge warning at import saying these code can break?
Or an alternative: allow the import, but don't include any example files in `pip install`. In this way a normal user will have no chance relying on these code with no compatibility. And only developers (which use tensorpack locally and hopefully know the risks) are able to import it.

**Comment by PatWie** [comment]
`find . -name "GAN.py" | wc -l` is **23**. And that's definitely not the best solution yet. 

I could life with a big read blinking warning my the terminal saying that " import tensorpack.examples is highly unstable" and using it "will initiate the end of the world."

**Comment by ppwwyyxx** [comment]
Locally I have a lot of copies of "imagenet_utils.py" around as well. Isn't there a time you want to modify GAN.py very quickly but don't want to affect the other code? That's why I prefer copying myself.

**Comment by ppwwyyxx** [comment]
I do not know how to achieve this without any super ugly path hacking, because `examples` is not under `tensorpack`.

**Comment by PatWie** [comment]
That's why I am asking. Having something like `tensorpack.hub` would be indeed really helpful.

**Comment by ppwwyyxx** [comment]
Closing since it seems there isn't a elegant way to make examples importable.
