### ISSUE TITLE
DoReFa Net paper question

### ISSUE THREAD

**Issue by tongwu92623** [tensorpack/tensorpack#963]
Hi,

Thank you for your help. Now I got a question about the data type in dorefa net. 
![image](https://user-images.githubusercontent.com/43963218/47888320-3d136f80-de1a-11e8-90a2-136c3da08cec.png)
In this paragraph, you said Ro is a k-bit fixed point integer, however, I print out the value and from the print out result, I think it should be the floating point value. I could get something wrong here, could you help me to understand this?

Best regards,

Tong Wu

**Comment by ppwwyyxx** [comment]
For anyone to better diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

In particular, I do not know what you did and what you've observed. Please do not describe what you did and what you saw, paste them.

**Comment by ppwwyyxx** [comment]
If I understand your questions correctly,
`round((2^k-1) r_i` is a k-bit fixed-point integer.
`r_o` is a k-bit fixed point number, but not an integer. 
But because `r_o * (2^k-1)` is fixed-point integer, the dot product can still be done with integer convolution kernel because you can ignore a coefficient and apply it back later.

**Comment by tongwu92623** [comment]
Got it, thx.
